In [2]:

%pip install -q mysql-connector-python pandas
import mysql.connector
import pandas as pd

DB_CONFIG = {
    "host": "mysql-olist-db-yoganinorahardian-acf4.h.aivencloud.com",
    "port": 27518,
    "user": "avnadmin",
    "password": "AVNS_veszJ1_IVpGLJ_IbS6q",
    "database": "olist_db",
}

TABLE_NAME = "fact_olist_order_line"

print("Konfigurasi siap.")
def run_query(conn, query):
    return pd.read_sql(query, conn)

conn = mysql.connector.connect(**DB_CONFIG)
print("Koneksi berhasil.")

queries = {
    "total_rows": f"SELECT COUNT(*) AS total_rows FROM {TABLE_NAME};",
    "min_max_purchase_ts": f"SELECT MIN(purchase_ts) AS min_purchase_ts, MAX(purchase_ts) AS max_purchase_ts FROM {TABLE_NAME};",
    "avg_review_score": f"SELECT AVG(review_score) AS avg_review_score FROM {TABLE_NAME};"
}

results = {}
for name, sql in queries.items():
    results[name] = run_query(conn, sql)

conn.close()
print("Query selesai dan koneksi ditutup.")
print("1) Total Rows")
display(results["total_rows"])

print("2) Min/Max purchase_ts")
display(results["min_max_purchase_ts"])

print("3) Average review_score")
display(results["avg_review_score"])

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.7/21.7 MB 60.2 MB/s eta 0:00:00
Konfigurasi siap.
Koneksi berhasil.

/tmp/ipykernel_1518/663841672.py:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(query, conn)

Query selesai dan koneksi ditutup.
1) Total Rows

   total_rows
0      112650

2) Min/Max purchase_ts

       min_purchase_ts      max_purchase_ts
0  2016-09-04 21:15:19  2018-09-03 09:06:57

3) Average review_score

   avg_review_score
0          4.032854